main:
alloc($r1, 2)
mov_int($t, 1)
store($r1, 0, $t)
mov_int($t, 42)
store($r1, 1, $t)
rtn1:
mov_reg($fun, @fun)
mov_reg($arg, @arg)
alloc($r2, 2)
mov_int($t, 3)
store($r2, 0, $t)
mov_label($t, rtn1)
store($r2, 1, $t)
mov_reg($t, $arg)
store($r2, 2, $t)
mov_reg(@res, $r2)
return()
load(@fun, $r2, 1)
mov_reg(@arg, $r1)
call(@fun)
mov_reg(r1, @res)
load($r2, $r1, 1)
print($r2)
mov_reg($G_main, $r1)
